# Generated by Django 3.2.9 on 2021-11-18 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="canvas",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="canvas",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
