# Generated by Django 3.2.9 on 2021-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_auto_20211118_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='drawing',
            field=models.TextField(default=''),
        ),
    ]
